// Dictionary data
const dictionaryData = [
    { japanese: "こんにちは", english: "Hello" },
    { japanese: "さようなら", english: "Goodbye" },
    { japanese: "ありがとう", english: "Thank you" },
    { japanese: "すみません", english: "Excuse me / Sorry" },
    { japanese: "はい", english: "Yes" },
    { japanese: "いいえ", english: "No" },
    { japanese: "ひと", english: "Person" },
    { japanese: "みず", english: "Water" },
    { japanese: "やま", english: "Mountain" },
    { japanese: "さくら", english: "Cherry blossom" },
    { japanese: "ねこ", english: "Cat" },
    { japanese: "いぬ", english: "Dog" },
    { japanese: "くるま", english: "Car" },
    { japanese: "でんしゃ", english: "Train" },
    { japanese: "じてんしゃ", english: "Bicycle" },
    { japanese: "とり", english: "Bird" },
    { japanese: "うみ", english: "Sea" },
    { japanese: "そら", english: "Sky" },
    { japanese: "はな", english: "Flower" }
];

// Kanji data
const kanjiData = [
    { kanji: "一", meaning: "one", kunyomi: "ひと", onyomi: "イチ" },
    { kanji: "二", meaning: "two", kunyomi: "ふた", onyomi: "ニ" },
    { kanji: "三", meaning: "three", kunyomi: "み", onyomi: "サン" },
    { kanji: "四", meaning: "four", kunyomi: "よん", onyomi: "シ" },
    { kanji: "五", meaning: "five", kunyomi: "いつ", onyomi: "ゴ" },
    { kanji: "六", meaning: "six", kunyomi: "む", onyomi: "ロク" },
    { kanji: "七", meaning: "seven", kunyomi: "なな", onyomi: "シチ" },
    { kanji: "八", meaning: "eight", kunyomi: "や", onyomi: "ハチ" },
    { kanji: "九", meaning: "nine", kunyomi: "ここの", onyomi: "キュウ" },
    { kanji: "十", meaning: "ten", kunyomi: "とお", onyomi: "ジュウ" }
];

// Flashcard sets
const flashcardSets = {
    hiragana: [
        { front: "あ", back: "a" },
        { front: "い", back: "i" },
        { front: "う", back: "u" },
        { front: "え", back: "e" },
        { front: "お", back: "o" },
        { front: "か", back: "ka" },
        { front: "き", back: "ki" },
        { front: "く", back: "ku" },
        { front: "け", back: "ke" },
        { front: "こ", back: "ko" },
        { front: "が", back: "ga" },
        { front: "ぎ", back: "gi" },
        { front: "ぐ", back: "gu" },
        { front: "げ", back: "ge" },
        { front: "ご", back: "go" },
        { front: "さ", back: "sa" },
        { front: "し", back: "shi" },
        { front: "す", back: "su" },
        { front: "せ", back: "se" },
        { front: "そ", back: "so" },
        { front: "ざ", back: "za" },
        { front: "じ", back: "ji" },
        { front: "ず", back: "zu" },
        { front: "ぜ", back: "ze" },
        { front: "ぞ", back: "zo" },
        { front: "た", back: "ta" },
        { front: "ち", back: "chi" },
        { front: "つ", back: "tsu" },
        { front: "て", back: "te" },
        { front: "と", back: "to" },
        { front: "だ", back: "da" },
        { front: "ぢ", back: "di" },
        { front: "づ", back: "du" },
        { front: "で", back: "de" },
        { front: "ど", back: "do" },
        { front: "な", back: "na" },
        { front: "に", back: "ni" },
        { front: "ぬ", back: "nu" },
        { front: "ね", back: "ne" },
        { front: "の", back: "no" },
        { front: "は", back: "ha" },
        { front: "ひ", back: "hi" },
        { front: "ふ", back: "fu" },
        { front: "へ", back: "he" },
        { front: "ほ", back: "ho" },
        { front: "ば", back: "ba" },
        { front: "び", back: "bi" },
        { front: "ぶ", back: "bu" },
        { front: "べ", back: "be" },
        { front: "ぼ", back: "bo" },
        { front: "ぱ", back: "pa" },
        { front: "ぴ", back: "pi" },
        { front: "ぷ", back: "pu" },
        { front: "ぺ", back: "pe" },
        { front: "ぽ", back: "po" },
        { front: "ま", back: "ma" },
        { front: "み", back: "mi" },
        { front: "む", back: "mu" },
        { front: "め", back: "me" },
        { front: "も", back: "mo" },
        { front: "や", back: "ya" },
        { front: "ゆ", back: "yu" },
        { front: "よ", back: "yo" },
        { front: "ら", back: "ra" },
        { front: "り", back: "ri" },
        { front: "る", back: "ru" },
        { front: "れ", back: "re" },
        { front: "ろ", back: "ro" },
        { front: "わ", back: "wa" },
        { front: "を", back: "wo" },
        { front: "ん", back: "n" },
    ],
    katakana: [
        { front: "ア", back: "a" },
        { front: "イ", back: "i" },
        { front: "ウ", back: "u" },
        { front: "エ", back: "e" },
        { front: "オ", back: "o" },
        { front: "カ", back: "ka" },
        { front: "キ", back: "ki" },
        { front: "ク", back: "ku" },
        { front: "ケ", back: "ke" },
        { front: "コ", back: "ko" },
        { front: "サ", back: "sa" },
        { front: "シ", back: "shi" },
        { front: "ス", back: "su" },
        { front: "セ", back: "se" },
        { front: "ソ", back: "so" },
        { front: "タ", back: "ta" },
        { front: "チ", back: "chi" },
        { front: "ツ", back: "tsu" },
        { front: "テ", back: "te" },
        { front: "ト", back: "to" },
        { front: "ナ", back: "na" },
        { front: "ニ", back: "ni" },
        { front: "ヌ", back: "nu" },
        { front: "ネ", back: "ne" },
        { front: "ノ", back: "no" },
        { front: "ハ", back: "ha" },
        { front: "ヒ", back: "hi" },
        { front: "フ", back: "fu" },
        { front: "ヘ", back: "he" },
        { front: "ホ", back: "ho" },
        { front: "マ", back: "ma" },
        { front: "ミ", back: "mi" },
        { front: "ム", back: "mu" },
        { front: "メ", back: "me" },
        { front: "モ", back: "mo" },
        { front: "ヤ", back: "ya" },
        { front: "ユ", back: "yu" },
        { front: "ヨ", back: "yo" },
        { front: "ラ", back: "ra" },
        { front: "リ", back: "ri" },
        { front: "ル", back: "ru" },
        { front: "レ", back: "re" },
        { front: "ロ", back: "ro" },
        { front: "ワ", back: "wa" },
        { front: "ヲ", back: "wo" },
        { front: "ン", back: "n" }

    ],
    kanji: [
        { front: "一", back: "one" },
        { front: "二", back: "two" },
        { front: "三", back: "three" },
        { front: "四", back: "four" },
        { front: "五", back: "five" },
        { front: "六", back: "six" },
        { front: "七", back: "seven" },
        { front: "八", back: "eight" },
        { front: "九", back: "nine" },
        { front: "十", back: "ten" },
    ],
    words: [
        { front: "こんにちは", back: "Hello" },
        { front: "さようなら", back: "Goodbye" },
        { front: "ありがとう", back: "Thank you" },
        { front: "すみません", back: "Excuse me" },
        { front: "はい", back: "Yes" },
        { front: "いいえ", back: "No" },
        { front: "ひと", back: "Person" },
        { front: "みず", back: "Water" },
        { front: "やま", back: "Mountain" },
        { front: "さくら", back: "Cherry blossom" }
    ]
};